export {
  STUDIO_CATEGORIES,
  STUDIO_TOP_TABS,
  STUDIO_SUB_GROUPS,
  STUDIO_VARIANTS,
  STUDIO_TEMPLATES,
  variantById,
  variantsForCategory,
  variantsForGroup,
  templateById,
  isAprVariant,
  isPoolMetricVariant,
  isProtocolVariant,
  type StudioCategory,
  type StudioTopTabId,
  type StudioSubGroup,
  type StudioVariantId,
  type StudioVariant,
  type StudioTemplateId,
} from './studioRegistry';
